
@startuml
Controller->ServiceProxy:调用serviceProxy
ServiceProxy->TransactionManager:开启事务
TransactionManager->TransactionInterceptor
TransactionInterceptor->RouteContextInterceptor: 数据源由路Context拦截器
RouteContextInterceptor->RouteContextInterceptor: 保存是否有事务信
RouteContextInterceptor->Service:开始业务处理
Service->Service1:调用Service1
Service1->Dao1:据routeContext做路由处理
Dao1->Dao1:访问数据
Dao1->Service1:返回数据
Service1->Service:
Service->RouteContextInterceptor:清除context数据，并返回
RouteContextInterceptor->TransactionInterceptor:
TransactionInterceptor->TransactionManager:业务处理完成
TransactionManager->ServiceProxy:提交事务
ServiceProxy->Controller:返回结果
@enduml
