
@startuml
Client->ServiceInterceptor:进入serviceProxy 拦截器
ServiceInterceptor->ServiceInterceptor:设置数据源context
ServiceInterceptor->TransactionInterceptor:进入事务拦截器
TransactionInterceptor->TransactionInterceptor:设置数据源context
TransactionManager<-TransactionInterceptor
TransactionManager->TransactionManager:开启事务
TransactionManager->Service:开始业务处理
Service->Service1:调用Service1
Service1->Dao1:据数据源context做路由处理
Dao1->Dao1:访问数据
Dao1->Service:返回数据
Service->TransactionManager:处理完业务
TransactionManager->TransactionManager:提交事务
TransactionManager->Client:返回结果
@enduml
